<a href="https://colab.research.google.com/github/Drorkalel/Python_DataScience/blob/main/Organizando_datframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Organizando DataFrames en Pandas

In [ ]:
import pandas as pd

In [ ]:
data = [[1,2,3],[4,5,6],[7,8,9]]
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
list('321')

['3', '2', '1']

In [ ]:
df = pd.DataFrame(data, list('321'), list('ZYX'))
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9

In [ ]:
df.sort_index(inplace = True) # Ordena las filas
df

   Z  Y  X
1  7  8  9
2  4  5  6
3  1  2  3

In [ ]:
df.sort_index(  axis = 1) # Se ve reflejado el orden de filas y columnas
df

   X  Y  Z
3  3  2  1
2  6  5  4
1  9  8  7

In [ ]:
df.sort_values(by = 'X', inplace = True)  # Se ordenan valores por orden ascendente columna X
df

   X  Y  Z
3  3  2  1
2  6  5  4
1  9  8  7